---
PORT: 3008
MONGODB:
  URL: 'mongodb://127.0.0.1:27017/hospital'
  DB: hospital

AUTH:
  SECRET: 'hospital'
  EXPIRES: '24h'

WECHAT:
  #APP_ID: 'wx8b48a6a3cccb1a2d'
  APP_ID: 'wx3dd0ab7b7c6c40fe'
  # APP_SECRET: '7d4fbf54118a9b64c2ca319735a7d6db'
  APP_SECRET: '87f0ba694625725332b55afa26d49c9b'
  SCOPE: 'snsapi_userinfo'
